<?php
/**
 * AppInfo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 阿波罗客户端
 *
 * 阿波罗客户端
 *
 * OpenAPI spec version: v0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AppInfo Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppInfo implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'appInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
'app_id' => 'string',
'org_id' => 'string',
'org_name' => 'string',
'owner_name' => 'string',
'owner_email' => 'string',
'data_change_created_by' => 'string',
'data_change_last_modified_by' => 'string',
'data_change_created_time' => 'string',
'data_change_last_modified_time' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
'app_id' => null,
'org_id' => null,
'org_name' => null,
'owner_name' => null,
'owner_email' => null,
'data_change_created_by' => null,
'data_change_last_modified_by' => null,
'data_change_created_time' => null,
'data_change_last_modified_time' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
'app_id' => 'appId',
'org_id' => 'orgId',
'org_name' => 'orgName',
'owner_name' => 'ownerName',
'owner_email' => 'ownerEmail',
'data_change_created_by' => 'dataChangeCreatedBy',
'data_change_last_modified_by' => 'dataChangeLastModifiedBy',
'data_change_created_time' => 'dataChangeCreatedTime',
'data_change_last_modified_time' => 'dataChangeLastModifiedTime'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
'app_id' => 'setAppId',
'org_id' => 'setOrgId',
'org_name' => 'setOrgName',
'owner_name' => 'setOwnerName',
'owner_email' => 'setOwnerEmail',
'data_change_created_by' => 'setDataChangeCreatedBy',
'data_change_last_modified_by' => 'setDataChangeLastModifiedBy',
'data_change_created_time' => 'setDataChangeCreatedTime',
'data_change_last_modified_time' => 'setDataChangeLastModifiedTime'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
'app_id' => 'getAppId',
'org_id' => 'getOrgId',
'org_name' => 'getOrgName',
'owner_name' => 'getOwnerName',
'owner_email' => 'getOwnerEmail',
'data_change_created_by' => 'getDataChangeCreatedBy',
'data_change_last_modified_by' => 'getDataChangeLastModifiedBy',
'data_change_created_time' => 'getDataChangeCreatedTime',
'data_change_last_modified_time' => 'getDataChangeLastModifiedTime'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['app_id'] = isset($data['app_id']) ? $data['app_id'] : null;
        $this->container['org_id'] = isset($data['org_id']) ? $data['org_id'] : null;
        $this->container['org_name'] = isset($data['org_name']) ? $data['org_name'] : null;
        $this->container['owner_name'] = isset($data['owner_name']) ? $data['owner_name'] : null;
        $this->container['owner_email'] = isset($data['owner_email']) ? $data['owner_email'] : null;
        $this->container['data_change_created_by'] = isset($data['data_change_created_by']) ? $data['data_change_created_by'] : null;
        $this->container['data_change_last_modified_by'] = isset($data['data_change_last_modified_by']) ? $data['data_change_last_modified_by'] : null;
        $this->container['data_change_created_time'] = isset($data['data_change_created_time']) ? $data['data_change_created_time'] : null;
        $this->container['data_change_last_modified_time'] = isset($data['data_change_last_modified_time']) ? $data['data_change_last_modified_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets app_id
     *
     * @return string
     */
    public function getAppId()
    {
        return $this->container['app_id'];
    }

    /**
     * Sets app_id
     *
     * @param string $app_id app_id
     *
     * @return $this
     */
    public function setAppId($app_id)
    {
        $this->container['app_id'] = $app_id;

        return $this;
    }

    /**
     * Gets org_id
     *
     * @return string
     */
    public function getOrgId()
    {
        return $this->container['org_id'];
    }

    /**
     * Sets org_id
     *
     * @param string $org_id org_id
     *
     * @return $this
     */
    public function setOrgId($org_id)
    {
        $this->container['org_id'] = $org_id;

        return $this;
    }

    /**
     * Gets org_name
     *
     * @return string
     */
    public function getOrgName()
    {
        return $this->container['org_name'];
    }

    /**
     * Sets org_name
     *
     * @param string $org_name org_name
     *
     * @return $this
     */
    public function setOrgName($org_name)
    {
        $this->container['org_name'] = $org_name;

        return $this;
    }

    /**
     * Gets owner_name
     *
     * @return string
     */
    public function getOwnerName()
    {
        return $this->container['owner_name'];
    }

    /**
     * Sets owner_name
     *
     * @param string $owner_name owner_name
     *
     * @return $this
     */
    public function setOwnerName($owner_name)
    {
        $this->container['owner_name'] = $owner_name;

        return $this;
    }

    /**
     * Gets owner_email
     *
     * @return string
     */
    public function getOwnerEmail()
    {
        return $this->container['owner_email'];
    }

    /**
     * Sets owner_email
     *
     * @param string $owner_email owner_email
     *
     * @return $this
     */
    public function setOwnerEmail($owner_email)
    {
        $this->container['owner_email'] = $owner_email;

        return $this;
    }

    /**
     * Gets data_change_created_by
     *
     * @return string
     */
    public function getDataChangeCreatedBy()
    {
        return $this->container['data_change_created_by'];
    }

    /**
     * Sets data_change_created_by
     *
     * @param string $data_change_created_by data_change_created_by
     *
     * @return $this
     */
    public function setDataChangeCreatedBy($data_change_created_by)
    {
        $this->container['data_change_created_by'] = $data_change_created_by;

        return $this;
    }

    /**
     * Gets data_change_last_modified_by
     *
     * @return string
     */
    public function getDataChangeLastModifiedBy()
    {
        return $this->container['data_change_last_modified_by'];
    }

    /**
     * Sets data_change_last_modified_by
     *
     * @param string $data_change_last_modified_by data_change_last_modified_by
     *
     * @return $this
     */
    public function setDataChangeLastModifiedBy($data_change_last_modified_by)
    {
        $this->container['data_change_last_modified_by'] = $data_change_last_modified_by;

        return $this;
    }

    /**
     * Gets data_change_created_time
     *
     * @return string
     */
    public function getDataChangeCreatedTime()
    {
        return $this->container['data_change_created_time'];
    }

    /**
     * Sets data_change_created_time
     *
     * @param string $data_change_created_time data_change_created_time
     *
     * @return $this
     */
    public function setDataChangeCreatedTime($data_change_created_time)
    {
        $this->container['data_change_created_time'] = $data_change_created_time;

        return $this;
    }

    /**
     * Gets data_change_last_modified_time
     *
     * @return string
     */
    public function getDataChangeLastModifiedTime()
    {
        return $this->container['data_change_last_modified_time'];
    }

    /**
     * Sets data_change_last_modified_time
     *
     * @param string $data_change_last_modified_time data_change_last_modified_time
     *
     * @return $this
     */
    public function setDataChangeLastModifiedTime($data_change_last_modified_time)
    {
        $this->container['data_change_last_modified_time'] = $data_change_last_modified_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
