<?php
/**
 * Field
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 阿波罗客户端
 *
 * 阿波罗客户端
 *
 * OpenAPI spec version: v0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Field Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Field implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'field';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'key' => 'string',
'value' => 'string',
'data_change_created_by' => 'string',
'data_change_last_modified_by' => 'string',
'data_change_created_time' => 'string',
'data_change_last_modified_time' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'key' => null,
'value' => null,
'data_change_created_by' => null,
'data_change_last_modified_by' => null,
'data_change_created_time' => null,
'data_change_last_modified_time' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'key' => 'key',
'value' => 'value',
'data_change_created_by' => 'dataChangeCreatedBy',
'data_change_last_modified_by' => 'dataChangeLastModifiedBy',
'data_change_created_time' => 'dataChangeCreatedTime',
'data_change_last_modified_time' => 'dataChangeLastModifiedTime'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'key' => 'setKey',
'value' => 'setValue',
'data_change_created_by' => 'setDataChangeCreatedBy',
'data_change_last_modified_by' => 'setDataChangeLastModifiedBy',
'data_change_created_time' => 'setDataChangeCreatedTime',
'data_change_last_modified_time' => 'setDataChangeLastModifiedTime'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'key' => 'getKey',
'value' => 'getValue',
'data_change_created_by' => 'getDataChangeCreatedBy',
'data_change_last_modified_by' => 'getDataChangeLastModifiedBy',
'data_change_created_time' => 'getDataChangeCreatedTime',
'data_change_last_modified_time' => 'getDataChangeLastModifiedTime'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['key'] = isset($data['key']) ? $data['key'] : null;
        $this->container['value'] = isset($data['value']) ? $data['value'] : null;
        $this->container['data_change_created_by'] = isset($data['data_change_created_by']) ? $data['data_change_created_by'] : null;
        $this->container['data_change_last_modified_by'] = isset($data['data_change_last_modified_by']) ? $data['data_change_last_modified_by'] : null;
        $this->container['data_change_created_time'] = isset($data['data_change_created_time']) ? $data['data_change_created_time'] : null;
        $this->container['data_change_last_modified_time'] = isset($data['data_change_last_modified_time']) ? $data['data_change_last_modified_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets key
     *
     * @return string
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string $key key
     *
     * @return $this
     */
    public function setKey($key)
    {
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string $value value
     *
     * @return $this
     */
    public function setValue($value)
    {
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets data_change_created_by
     *
     * @return string
     */
    public function getDataChangeCreatedBy()
    {
        return $this->container['data_change_created_by'];
    }

    /**
     * Sets data_change_created_by
     *
     * @param string $data_change_created_by data_change_created_by
     *
     * @return $this
     */
    public function setDataChangeCreatedBy($data_change_created_by)
    {
        $this->container['data_change_created_by'] = $data_change_created_by;

        return $this;
    }

    /**
     * Gets data_change_last_modified_by
     *
     * @return string
     */
    public function getDataChangeLastModifiedBy()
    {
        return $this->container['data_change_last_modified_by'];
    }

    /**
     * Sets data_change_last_modified_by
     *
     * @param string $data_change_last_modified_by data_change_last_modified_by
     *
     * @return $this
     */
    public function setDataChangeLastModifiedBy($data_change_last_modified_by)
    {
        $this->container['data_change_last_modified_by'] = $data_change_last_modified_by;

        return $this;
    }

    /**
     * Gets data_change_created_time
     *
     * @return string
     */
    public function getDataChangeCreatedTime()
    {
        return $this->container['data_change_created_time'];
    }

    /**
     * Sets data_change_created_time
     *
     * @param string $data_change_created_time data_change_created_time
     *
     * @return $this
     */
    public function setDataChangeCreatedTime($data_change_created_time)
    {
        $this->container['data_change_created_time'] = $data_change_created_time;

        return $this;
    }

    /**
     * Gets data_change_last_modified_time
     *
     * @return string
     */
    public function getDataChangeLastModifiedTime()
    {
        return $this->container['data_change_last_modified_time'];
    }

    /**
     * Sets data_change_last_modified_time
     *
     * @param string $data_change_last_modified_time data_change_last_modified_time
     *
     * @return $this
     */
    public function setDataChangeLastModifiedTime($data_change_last_modified_time)
    {
        $this->container['data_change_last_modified_time'] = $data_change_last_modified_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
