<?php
/**
 * FieldPutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 阿波罗客户端
 *
 * 阿波罗客户端
 *
 * OpenAPI spec version: v0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FieldPutTest Class Doc Comment
 *
 * @category    Class
 * @description FieldPut
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FieldPutTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FieldPut"
     */
    public function testFieldPut()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "data_change_last_modified_by"
     */
    public function testPropertyDataChangeLastModifiedBy()
    {
    }

    /**
     * Test attribute "data_change_created_by"
     */
    public function testPropertyDataChangeCreatedBy()
    {
    }
}
