<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 阿波罗客户端
 *
 * 阿波罗客户端
 *
 * OpenAPI spec version: v0.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteField
     *
     * 删除配置接口.
     *
     */
    public function testDeleteField()
    {
    }

    /**
     * Test case for getAppInfo
     *
     * 获取App信息.
     *
     */
    public function testGetAppInfo()
    {
    }

    /**
     * Test case for getClusters
     *
     * 获取集群接口.
     *
     */
    public function testGetClusters()
    {
    }

    /**
     * Test case for getEnvClustersById
     *
     * 获取App的环境，集群信息.
     *
     */
    public function testGetEnvClustersById()
    {
    }

    /**
     * Test case for getField
     *
     * 读取配置接口.
     *
     */
    public function testGetField()
    {
    }

    /**
     * Test case for getLock
     *
     * 获取某个Namespace当前编辑人接口.
     *
     */
    public function testGetLock()
    {
    }

    /**
     * Test case for getNamespace
     *
     * 获取某个Namespace信息接口.
     *
     */
    public function testGetNamespace()
    {
    }

    /**
     * Test case for getNamespaces
     *
     * 获取集群下所有Namespace信息接口.
     *
     */
    public function testGetNamespaces()
    {
    }

    /**
     * Test case for getReleases
     *
     * 获取生效配置接口.
     *
     */
    public function testGetReleases()
    {
    }

    /**
     * Test case for postClusters
     *
     * 创建集群接口.
     *
     */
    public function testPostClusters()
    {
    }

    /**
     * Test case for postField
     *
     * 新增配置接口.
     *
     */
    public function testPostField()
    {
    }

    /**
     * Test case for postNamespace
     *
     * 创建Namespace.
     *
     */
    public function testPostNamespace()
    {
    }

    /**
     * Test case for postReleases
     *
     * 发布配置接口.
     *
     */
    public function testPostReleases()
    {
    }

    /**
     * Test case for putField
     *
     * 修改配置接口.
     *
     */
    public function testPutField()
    {
    }

    /**
     * Test case for rollback
     *
     * 回滚已发布配置接口.
     *
     */
    public function testRollback()
    {
    }
}
